#include "global.h"
void init_liste(t_liste*);
int liste_vide(t_liste*);
int hors_liste(t_liste*);
void en_tete(t_liste*);
void en_queue(t_liste*);
void precedent(t_liste*);
void suivant(t_liste*);
void valeur_elt(t_liste*,int*);
void modif_elt(t_liste*,int);
void oter_elt(t_liste*);
void ajout_droit(t_liste*,int);
void ajout_gauche(t_liste*,int);
