#include "global.h"
void init_liste_noeud(t_liste_noeud*);
int liste_vide_noeud(t_liste_noeud*);
int hors_liste_noeud(t_liste_noeud*);
void en_tete_noeud(t_liste_noeud*);
void en_queue_noeud(t_liste_noeud*);
void precedent_noeud(t_liste_noeud*);
void suivant_noeud(t_liste_noeud*);
void valeur_elt_noeud(t_liste_noeud*,t_noeud*);
void modif_elt_noeud(t_liste_noeud*,t_noeud);
void oter_elt_noeud(t_liste_noeud*);
void ajout_droit_noeud(t_liste_noeud*,t_noeud);
void ajout_gauche_noeud(t_liste_noeud*,t_noeud);
